language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1

install:
  - composer install --no-interaction --prefer-dist

script:
  - composer lint
  - composer cs
  - ./vendor/bin/phpunit --coverage-clover=./coverage.xml
  - composer stan

after_success:
  - >
    if [ $TRAVIS_PHP_VERSION == "7.1" ]; then
    wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    && php ./coveralls.phar --verbose
    || true; fi
